version: '3.2'

networks:
  hommler:

services:
  phpHommler:
    image: yiisoftware/yii2-php:7.4-apache
    container_name: phpHommler
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
    networks:
      hommler:

  mysqlHommler:
    image: mysql:8
    container_name: 'mysqlHommler'
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "yii2basic"
      MYSQL_USER: "yii2basic"
      MYSQL_PASSWORD: "123456"
    networks:
      hommler:

  db_adminHommler:
    image: phpmyadmin/phpmyadmin:5.0.1
    container_name: 'db-adminHommler'
    depends_on:
      - mysqlHommler
    environment:
      PMA_HOST: mysqlHommler
      PMA_PORT: 3306
    ports:
      - '7777:80'
    networks:
      hommler:


volumes:
  db_data: